### ISSUE TITLE
תהליך התחלה

### ISSUE THREAD

**Issue by erelsgl** [gamedev-srg/Hide-and-Seek-Royale#2]
לא מצאתי את תהליך ההתחלה של המשלק - התהליך שבו המשחק מסביר לשחקן מה הוא אמור לעשות.

**Comment by gidon285** [comment]
היי אראל, היה בלבול מחבינת הגיטהאבים מכיוון שלהבדיל מהמשחקים החדשים פה הגיטהאב נשאר זהה. הקישור שונה.
תודה על ההערה.
