### ISSUE TITLE
משחק "מחבואים"

### ISSUE THREAD

**Issue by erelsgl** [gamedev-srg/Hide-and-Seek-Royale#3]
כיוון שהמשחק נקרא "מחבואים", אולי צריך להדגיש פחות את היריות ויותר את ההתחבאות (שלא ייראה יותר מדי דומה לפורטנייט וכד', אלא סגנון אחר).

**Comment by gidon285** [comment]
היי אראל.
כרגע אנחנו עובדים על הפונקציונליות העיקרית של המשחק ובהמשך נוסיף סוגי משחק שונים, בהם גם גרסא ללא יריות
