### ISSUE TITLE
הטוטוריאל נתקע

### ISSUE THREAD

**Issue by erelsgl** [gamedev-srg/Hide-and-Seek-Royale#4]
הטוטוריאל נתקע:
![image](https://user-images.githubusercontent.com/1462215/148102403-6064bdf9-6a31-434d-be0b-2b07ca95d8d5.png)

**Comment by ShmuelLa** [comment]
טופל. פשוט עדיין לא העלנו את הגרסה הסופית, עלתה חדשה הרגע.
נשמח לעוד הערות :)

**Comment by erelsgl** [comment]
עכשיו הטוטוריאל עובד, אבל כשהוא נגמר, העכבר נעלם ואני לא יכול לחזור למשחק.
![image](https://user-images.githubusercontent.com/1462215/148107667-e6d4172d-21f7-485b-a477-75509fa416f9.png)

**Comment by ShmuelLa** [comment]
בטיפול

**Comment by ShmuelLa** [comment]
טופל
