### ISSUE TITLE
מלכודות

### ISSUE THREAD

**Issue by erelsgl** [gamedev-srg/Hide-and-Seek-Royale#6]
בטוטוריאל, לא שמתי לב שיש התייחסות למלכודות (ייתכן שפספסתי).

גם במשחק עצמו, לא ברור מה בדיוק עוזרות המלכודות - הרי בסופו של דבר האתגר הוא למצוא את אלה שמתחבאים - והם לא נכנסים למלכודות. לכאורה מלכודות רק מסכנות את השחקן עצמו.

**Comment by ShmuelLa** [comment]
אנחנו נדאג להבהיר את הנושא בטוטוריאל בגרסה שנעלה בעוד מספר דקות.

בגדול, האתר המרכזי זה למצוא אותם בזמן אבל אתה יכול גם להניח מלכודות שהם יעלו עליהם בזמן שהם בורחים ממך. אתה כמובן צודק שהמלכודות מסכנות גם את השחקן עצמו וזה גם חלק מהאתגר שהוספנו לאור משובים קודמים.
כמובן שגם זה יודגש בטוטוריאל.

**Comment by gidon285** [comment]
היי אראל, הועלתה גרסא ברורה יותר של המשחק.
